"use strict"; //TREAT ALL JAVASCRIPT CODE AS NEWER VERSION

//alert() -> THIS FUNCTION WILL NOT WORK BECAUSE WE ARE USING node js AND NOT BROWSER

/*
IT IS NOT COMPULSORY TO DEFINE THE DATA TYPE IN JS, WE CAN JUST USE let KEYWORD

DATA TYPES IN JS:
number->INTEGER VALUE
bigint->INTEGER VALUE WITH BIGGER RANGE
string->""
boolean->true/false
null->STANDALONE VALUE
undefined->WHEN VALUE IS NOT ASSIGNED TO A VARIABLE eg.let name
symbol->UNIQUE VALUE



object-
*/

//typeof FUNCTION RETURNS THE DATA TYPE OF GIVEN PARAMETER
console.log(typeof "vaibhav"); 

console.log(typeof null);// THIS WILL RETURN object AS OUTPUT AND NOT null